services:

  webapi:
    container_name: "fastapi_voteapp_webapi"
    build:
      context: ./fastapiapp
    image: fastapi_image
    volumes:
      - ./fastapiapp:/fastapiapp
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    container_name: "vite_voteapp_frontend"
    build:
      context: ./viteapp
    image: vite_image
    volumes:
      - ./viteapp:/viteapp
    ports:
      - 5173:5173 # 本番で動かす際はコメントアウト
    tty: true

  db:
    image: mongo:latest
    container_name: mongodb_voteapp_db
    ports:
      - "27017:27017"
    environment:
      # TODO envファイルで管理
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    # volumes:
      # - mongodb_data:/data/db

# volumes:
  # mongodb_data: